name: calculator
description: Calculator preteZ

publish_to: "pretez"

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  google_fonts: ^5.1.0
  math_expressions: ^2.3.0
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
  

  flutter_lints: ^2.0.0
flutter_icons:
  android: true
  ios: true
  image_path: lib/assets/logo.png
flutter:
  uses-material-design: true
  assets:
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/example/
    - android/app/src/main/kotlin/com/example/calculator_pretez/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/gradle/
    - android/gradle/wrapper/


